Dear User,

Someone, possibly you, requested the following user information from our 
Forgotten Password utility at {$smarty.server.SERVER_NAME}. If you did not 
request this information you can disregard this email, since this information 
was only sent to this email address and not displayed at the time it was 
requested.

Email Address: {$row.email}
Password: {$row.password}

If you have any other problems logging into the website please feel free to
contact us at http://{$smarty.server.SERVER_NAME}{$smarty.server.SCRIPT_NAME}/contact

--------------------------------------------------------------------------------
This email was automatically generated by our website at your request. Please
do not reply directly to this email.
--------------------------------------------------------------------------------
